name: build-docs
run-name: ${{ github.actor }} is building documentation
on:
  pull_request:
  push:
    branches: [main]
jobs:
  Build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build postman docs
        run: |
          mkdir docs
          ./postman/postmanerator --output=./docs/index.html --collection=./postman/collection.json
      - name: commit docs
        run: |
           git config --global user.email "29102292+mghmay@users.noreply.github.com"
          git config --global user.name "docs-bot"
          git add docs
          git commit -m "Make docs"
          git push
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
