name: build-docs
run-name: ${{ github.actor }} is building documentation
on:
  pull_request:
  push:
    branches: [main]
jobs:
  Build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build postman docs
        run: |
          ./postman/postmanerator --output=./docs/index.html --collection=./postman/collection.json
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
